<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="Testcontainers.MsSql" Version="4.13.0" />
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>
    
    <ItemGroup>
        <Content Include="..\01_create_tables.sql" Link="sql\01_create_tables.sql"
                 CopyToOutputDirectory="PreserveNewest"/>
        <Content Include="..\02_seed_data.sql" Link="sql\02_seed_data.sql"
                 CopyToOutputDirectory="PreserveNewest"/>
        <Content Include="..\queries\*.sql" Link="sql\queries\%(Filename)%(Extension)"
                 CopyToOutputDirectory="PreserveNewest"/>
        <Content Include="..\query-plans\18_indexes.sql" Link="sql\query-plans\18_indexes.sql"
                 CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

</Project>