CREATE TABLE Restaurants (
                             RestaurantId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             Name         VARCHAR(100) NOT NULL,
                             Address      VARCHAR(255),
                             PhoneNumber  VARCHAR(20),
                             OpeningHours VARCHAR(100)
);

CREATE TABLE Customers (
                           CustomerId  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           FirstName   VARCHAR(50) NOT NULL,
                           LastName    VARCHAR(50) NOT NULL,
                           Email       VARCHAR(255),
                           PhoneNumber VARCHAR(20)
);

CREATE TABLE Tables (
                        TableId      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        RestaurantId INT NOT NULL,
                        Capacity     INT NOT NULL,
                        CONSTRAINT FK_Tables_Restaurant FOREIGN KEY (RestaurantId) REFERENCES Restaurants(RestaurantId)
);

CREATE TABLE MenuItems (
                           ItemId       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           RestaurantId INT NOT NULL,
                           Name         VARCHAR(100) NOT NULL,
                           Description  VARCHAR(500),
                           Price        NUMERIC(10,2) NOT NULL,
                           CONSTRAINT FK_MenuItems_Restaurant FOREIGN KEY (RestaurantId) REFERENCES Restaurants(RestaurantId)
);

CREATE TABLE Employees (
                           EmployeeId   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           RestaurantId INT NOT NULL,
                           FirstName    VARCHAR(50) NOT NULL,
                           LastName     VARCHAR(50) NOT NULL,
                           Position     VARCHAR(50) NOT NULL,
                           CONSTRAINT FK_Employees_Restaurant FOREIGN KEY (RestaurantId) REFERENCES Restaurants(RestaurantId)
);

CREATE TABLE Reservations (
                              ReservationId   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              CustomerId      INT NOT NULL,
                              RestaurantId    INT NOT NULL,
                              TableId         INT NOT NULL,
                              ReservationDate TIMESTAMP NOT NULL,
                              PartySize       INT NOT NULL,
                              CONSTRAINT FK_Reservations_Customer   FOREIGN KEY (CustomerId)   REFERENCES Customers(CustomerId),
                              CONSTRAINT FK_Reservations_Restaurant FOREIGN KEY (RestaurantId) REFERENCES Restaurants(RestaurantId),
                              CONSTRAINT FK_Reservations_Table      FOREIGN KEY (TableId)      REFERENCES Tables(TableId)
);

CREATE TABLE Orders (
                        OrderId       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ReservationId INT NOT NULL,
                        EmployeeId    INT NOT NULL,
                        OrderDate     TIMESTAMP NOT NULL,
                        TotalAmount   NUMERIC(10,2) NOT NULL,
                        CONSTRAINT FK_Orders_Reservation FOREIGN KEY (ReservationId) REFERENCES Reservations(ReservationId),
                        CONSTRAINT FK_Orders_Employee    FOREIGN KEY (EmployeeId)    REFERENCES Employees(EmployeeId)
);

CREATE TABLE OrderItems (
                            OrderItemId INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            OrderId     INT NOT NULL,
                            ItemId      INT NOT NULL,
                            Quantity    INT NOT NULL,
                            CONSTRAINT FK_OrderItems_Order    FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
                            CONSTRAINT FK_OrderItems_MenuItem FOREIGN KEY (ItemId)  REFERENCES MenuItems(ItemId)
);