-- 16_trg_audit_reservation.sql
CREATE TABLE IF NOT EXISTS AuditLog (
                                        AuditId         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        RestaurantId    INT,
                                        TableId         INT,
                                        ReservationDate TIMESTAMP,
                                        ChangeDate      TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION trg_audit_reservation_fn()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO AuditLog (RestaurantId, TableId, ReservationDate, ChangeDate)
    VALUES (NEW.RestaurantId, NEW.TableId, NEW.ReservationDate, NOW());
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_AuditReservation ON Reservations;
CREATE TRIGGER trg_AuditReservation
    AFTER INSERT ON Reservations
    FOR EACH ROW
EXECUTE FUNCTION trg_audit_reservation_fn();

-- demo (rolled back so it leaves no trace)
BEGIN;
INSERT INTO Reservations (CustomerId, RestaurantId, TableId, ReservationDate, PartySize)
VALUES (1, 1, 1, NOW() + INTERVAL '30 days', 2);

SELECT * FROM AuditLog ORDER BY AuditId DESC LIMIT 5;
ROLLBACK;